version: '3'
services:
  dev_database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dev_jms
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres:/var/lib/postgresql/data

  test_database:
    image: postgres
    restart: always
    ports:
      - '5433:5433'
    environment:
      POSTGRES_DB: dev_jms_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

volumes:
  postgres: